version: "3"
services:
  db:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    ports:
      - "5432:5432"
  app:
    image: nodeimage
    container_name: nodecontainer
    build: ./
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      # - DATABASE=test
      - DATABASE_NAME=postgres
      - DATABASE_PASS=postgres
      - HOST=db
      - SECRET_KEY=secret
